on:
  push:
    branches: [ develop, bugfix/*, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-matrix.yml@9760f8ddcf2d7d2b4aa89b7c045626615c0bef58